/* PROTOTYPE — throwaway. Rallon build list copied verbatim from live-report.html (the design) so the
   bike page renders the same 32 parts in 9 categories. Exposed as a global for prototype-profile.html. */
(function () {
var DATA = [
  {
    id: "suspension",
    icon: "i-suspension",
    cs: "Odpružení",
    en: "Suspension",
    parts: [
      {
        cs: "Vidlice",
        en: "Fork",
        brand: "Fox",
        model: "38 Factory GRIP2",
        spec: "170 mm · 29″ · Kabolt-X 15×110",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Tlumič",
        en: "Shock",
        brand: "Fox",
        model: "Float X2 Factory",
        spec: "205 × 65 mm · trunnion",
        since: { cs: "od nového kola", en: "since new" },
      },
    ],
  },
  {
    id: "frame",
    icon: "i-frame",
    cs: "Rám",
    en: "Frame",
    parts: [
      {
        cs: "Rám",
        en: "Frame",
        brand: "Orbea",
        model: "Rallon M-LTD",
        spec: "carbon OMR · vel. L · 2023",
        since: { cs: "4. 4. 2023", en: "4 Apr 2023" },
        serial: "WOB23K4••••21",
      },
      {
        cs: "Hanger",
        en: "Hanger",
        brand: "Orbea",
        model: "1042 UDH",
        spec: "UDH kompatibilní",
        since: { cs: "8. 8. 2026", en: "8 Aug 2026" },
      },
    ],
  },
  {
    id: "cockpit",
    icon: "i-cockpit",
    cs: "Kokpit",
    en: "Cockpit",
    parts: [
      {
        cs: "Hlavové složení",
        en: "Headset",
        brand: "Acros",
        model: "Blocklock",
        spec: "ZS56/28,6 · ZS56/40",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Představec",
        en: "Stem",
        brand: "Race Face",
        model: "Turbine R 35",
        spec: "40 mm · 35 mm · 0°",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Řídítka",
        en: "Handlebar",
        brand: "OneUp",
        model: "Carbon Handlebar",
        spec: "800 mm · 35 mm · rise 20 mm",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
      {
        cs: "Gripy",
        en: "Grips",
        brand: "Ergon",
        model: "GA3",
        spec: "vel. L · černá",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
    ],
  },
  {
    id: "saddle",
    icon: "i-saddle",
    cs: "Sedlo a sedlovka",
    en: "Saddle & Seatpost",
    parts: [
      {
        cs: "Sedlo",
        en: "Saddle",
        brand: "Ergon",
        model: "SM Enduro Comp",
        spec: "M/L · 145 mm",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Sedlovka",
        en: "Seatpost",
        brand: "OneUp",
        model: "Dropper V2",
        spec: "210 mm zdvih · 31,6 mm",
        since: { cs: "od nového kola", en: "since new" },
      },
    ],
  },
  {
    id: "wheels",
    icon: "i-wheels",
    cs: "Kola",
    en: "Wheels",
    parts: [
      {
        cs: "Ráfek přední",
        en: "Rim, front",
        brand: "DT Swiss",
        model: "EX 511",
        spec: "29″ · 30 mm vnitřní · 32 děr",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Ráfek zadní",
        en: "Rim, rear",
        brand: "DT Swiss",
        model: "EX 511",
        spec: "29″ · 30 mm vnitřní · 32 děr",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Plášť přední",
        en: "Tire, front",
        brand: "Maxxis",
        model: "Assegai",
        spec: "29 × 2,5″ · EXO+ · MaxxGrip",
        since: { cs: "12. 6. 2026", en: "12 Jun 2026" },
      },
      {
        cs: "Plášť zadní",
        en: "Tire, rear",
        brand: "Maxxis",
        model: "Minion DHR II",
        spec: "29 × 2,4″ · DoubleDown · MaxxTerra",
        since: { cs: "12. 6. 2026", en: "12 Jun 2026" },
      },
      {
        cs: "Náboj přední",
        en: "Hub, front",
        brand: "DT Swiss",
        model: "350",
        spec: "Boost 110 × 15",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Náboj zadní",
        en: "Hub, rear",
        brand: "DT Swiss",
        model: "350",
        spec: "Boost 148 × 12 · 54 t ratchet",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Osa",
        en: "Axle",
        brand: "DT Swiss",
        model: "RWS Plug-In",
        spec: "12 × 148 mm",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Inserty",
        en: "Inserts",
        brand: "CushCore",
        model: "Pro",
        spec: "29″ · pár",
        since: { cs: "12. 6. 2026", en: "12 Jun 2026" },
      },
      {
        cs: "Ventilky",
        en: "Valves",
        brand: "Muc-Off",
        model: "Big Bore",
        spec: "44 mm · pár",
        since: { cs: "12. 6. 2026", en: "12 Jun 2026" },
      },
      {
        cs: "Tmel",
        en: "Sealant",
        brand: "Stan's",
        model: "Race Sealant",
        spec: "60 ml na kolo",
        since: { cs: "doplněno 12. 8. 2026", en: "topped up 12 Aug 2026" },
      },
    ],
  },
  {
    id: "drivetrain",
    icon: "i-drivetrain",
    cs: "Pohon",
    en: "Drivetrain",
    parts: [
      {
        cs: "Řadicí páka",
        en: "Shifter",
        brand: "SRAM",
        model: "GX Eagle AXS",
        spec: "12 rychlostí · bezdrátová",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Přehazovačka",
        en: "Derailleur",
        brand: "SRAM",
        model: "X01 Eagle AXS",
        spec: "12 rychlostí · max 52 z.",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Kliky",
        en: "Crank",
        brand: "SRAM",
        model: "X01 Eagle",
        spec: "170 mm · DUB · 55 mm chainline",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Převodník",
        en: "Chainring",
        brand: "SRAM",
        model: "X-Sync 2",
        spec: "32 z. · direct mount",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
      {
        cs: "Řetěz",
        en: "Chain",
        brand: "SRAM",
        model: "GX Eagle",
        spec: "126 článků · 12 rychlostí",
        id: "chain",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
      {
        cs: "Kazeta",
        en: "Cassette",
        brand: "SRAM",
        model: "XG-1275",
        spec: "10–52 z. · XD",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
    ],
  },
  {
    id: "brakes",
    icon: "i-brakes",
    cs: "Brzdy",
    en: "Brakes",
    parts: [
      {
        cs: "Brzdové páky",
        en: "Brake levers",
        brand: "SRAM",
        model: "Code RSC",
        spec: "4pístkové · pár",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Kotouč přední",
        en: "Rotor, front",
        brand: "SRAM",
        model: "Centerline X",
        spec: "200 mm · 6 děr",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Kotouč zadní",
        en: "Rotor, rear",
        brand: "SRAM",
        model: "Centerline X",
        spec: "180 mm · 6 děr",
        since: { cs: "od nového kola", en: "since new" },
      },
      {
        cs: "Destičky přední",
        en: "Brake pads, front",
        brand: "SRAM",
        model: "Code metalické",
        spec: "metalické · pár",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
      {
        cs: "Destičky zadní",
        en: "Brake pads, rear",
        brand: "SRAM",
        model: "Code metalické",
        spec: "metalické · pár",
        since: { cs: "21. 4. 2026", en: "21 Apr 2026" },
      },
    ],
  },
  {
    id: "ebike",
    icon: "i-ebike",
    cs: "E-bike",
    en: "E-bike",
    parts: [],
    empty: {
      cs: "Tohle kolo není elektro. Kategorie se objeví, jakmile v aplikaci přibude motor nebo baterie.",
      en: "This bike is not an e-bike. The category fills in as soon as a motor or battery is added in the app.",
    },
  },
  {
    id: "other",
    icon: "i-other",
    cs: "Ostatní",
    en: "Other",
    parts: [
      {
        cs: "Pedály",
        en: "Pedals",
        brand: "Crankbrothers",
        model: "Mallet DH",
        spec: "nášlapné · vložky +1 mm",
        since: { cs: "od nového kola", en: "since new" },
      },
    ],
  },
];
  window.RALLON_DATA = DATA;
})();
