/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["User getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user by given ID */
        patch: operations["User updateUser"];
        trace?: never;
    };
    "/api/users/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user */
        post: operations["User createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth refreshUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth googleReceiveToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Bike createBike"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bike searchBikeExternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/external/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bike searchComponentsExternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/form-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bike formOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bike findUserBikes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bike findBike"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["Bike update"];
        trace?: never;
    };
    "/api/bike/delsoft/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Bike deleteSoft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike/delhard/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Bike deleteHard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BikeEvent create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/group-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BikeEvent getActionsOnGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/find-all/{bikeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BikeEvent findAllBikeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BikeEvent findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/delsoft/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["BikeEvent softDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bike-events/delhard/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["BikeEvent hardDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Component createComponentType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/default-components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Component getDefaultComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Component getGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/mounted-components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Component getMountedComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new organization */
        post: operations["Organization createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get members of an organization */
        get: operations["Organization getMembers"];
        put?: never;
        /** Add a member to organization */
        post: operations["Organization addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization by ID */
        get: operations["Organization getOrganization"];
        put?: never;
        post?: never;
        /** Soft delete organization by ID */
        delete: operations["Organization deleteOrganization"];
        options?: never;
        head?: never;
        /** Update organization by ID */
        patch: operations["Organization updateOrganization"];
        trace?: never;
    };
    "/api/organizations/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from organization */
        delete: operations["Organization removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strava/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build the Strava authorize URL for the current user */
        get: operations["Strava connectStrava"];
        put?: never;
        post?: never;
        /** Unlink the current user's Strava account */
        delete: operations["Strava disconnectStrava"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strava/gear-linking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's Strava and BikeCheck bikes for linking */
        get: operations["Strava listUnmatchedStravaGear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Link a Strava bike to a BikeCheck bike */
        patch: operations["Strava linkStravaGear"];
        trace?: never;
    };
    "/api/strava/pending-activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rides that arrived without a bike the app could resolve */
        get: operations["Strava listPendingActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strava/pending-activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one pending ride by its Strava activity id */
        get: operations["Strava getPendingActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strava/pending-activities/{activityId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a pending ride to a BikeCheck bike */
        post: operations["Strava resolvePendingActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register FCM token for the current user */
        post: operations["Notification registerFcmToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications for the current user */
        get: operations["Notification list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: operations["Notification markRead"];
        trace?: never;
    };
    "/api/reports/bikes/{bikeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reports for a specific bike */
        get: operations["Report listForBike"];
        put?: never;
        /** Generate a shareable report for a bike */
        post: operations["Report create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all reports for the current user */
        get: operations["Report listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Revoke a report link */
        patch: operations["Report revoke"];
        trace?: never;
    };
    "/api/reports/public/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public view of a report by its share token */
        get: operations["Report getPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /** @example 1 */
            id: number;
            /** @example John Doe */
            name: string;
            email: string;
            /** @example https://example.com/avatar.jpg */
            avatar_url: Record<string, never> | null;
            /** @example en */
            language: Record<string, never> | null;
            /** @example czk */
            currency: Record<string, never> | null;
            /** @example 70 */
            weight_kg: Record<string, never> | null;
            /** @example true */
            is_active: boolean;
            /** @example 20678962 */
            strava_athlete_id: Record<string, never> | null;
            /** @example 2024-01-01T12:00:00Z */
            last_login_at: Record<string, never>;
            /**
             * Format: date-time
             * @example 2024-01-01T12:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-02T12:00:00Z
             */
            updated_at: string;
        };
        CreateUserDto: {
            /** @example John Doe */
            name: string;
            /** @example john.doe@example.com */
            email: string;
            /** @example strongPassword123 */
            password: string;
            /** @example en */
            language: string;
        };
        UpdateUserDto: {
            /** @example John Doe */
            name: string;
            /** @example en */
            language: string;
            /** @example czk */
            currency: string;
            /** @example 70 */
            weight_kg: number;
            /** @example https://example.com/avatar.jpg */
            avatar_url: string;
        };
        LoginDto: {
            /** @example jaffa@jaffa.com */
            email: string;
            /** @example jaffajaffa123 */
            password: string;
        };
        GoogleTokenDto: {
            /** @example eyJhbGciOiJSUzI1NiIsImtpZCI6... */
            idToken: string;
        };
        CreateBikeDto: {
            /** @example 1 */
            user_id?: number;
            /** @example Trek */
            bike_brand: string;
            /** @example true */
            ebike: boolean;
            /** @example true */
            has_front_suspension: boolean;
            /** @example false */
            has_rear_suspension: boolean;
            /** @example Domane SL7 */
            bike_model?: string;
            /** @example 1 */
            organization_id?: number;
            /** @example Tarmac SL7 */
            bikename?: string;
            /** @example 2024 */
            year?: number;
            /** @example Serviced bike, top health */
            description?: string;
            /** @example 29" */
            wheel_size?: string;
            /** @example L */
            bike_size?: string;
            /** @example Enduro */
            bike_type?: string;
            /** @example 1540 */
            total_km?: number;
            /** @example https://example.com/bike-image.jpg */
            image_url?: string;
        };
        CreateMountedComponentsDto: {
            /** @example 1 */
            bike_id?: number;
            /** @example 12 */
            component_type_id: number;
            /** @example Fox 38 Factory Grip2 */
            component_desc?: string | null;
            /** @example Front */
            position?: string | null;
            /**
             * Format: date-time
             * @example 2026-03-26T10:00:00.000Z
             */
            mounted_at?: string | null;
            /** @example 1200 */
            total_km?: number | null;
            /** @example true */
            is_active?: boolean | null;
            /** @example Mounted after spring service */
            note?: string | null;
            /** @example 2 */
            interval_id?: number | null;
        };
        CreateBikeWithComponentsDto: {
            bike: components["schemas"]["CreateBikeDto"];
            components: components["schemas"]["CreateMountedComponentsDto"][];
        };
        ResponseBikeDto: {
            /** @example 1 */
            id: number;
            /** @example 15 */
            user_id: number;
            /** @example true */
            ebike: boolean;
            /** @example 10 */
            organization_id: Record<string, never> | null;
            /** @example Specialized */
            bike_brand: string | null;
            /** @example Stumpjumper */
            bike_model: Record<string, never> | null;
            /** @example https://example.com/bike-image.jpg */
            image_url: Record<string, never> | null;
            /** @example 1 */
            bike_type_id: Record<string, never> | null;
            /** @example Tarmac SL7 */
            bikename: Record<string, never> | null;
            /** @example 2024 */
            year: Record<string, never> | null;
            /** @example Serviced bike, top health */
            description: Record<string, never> | null;
            /** @example 29" */
            wheel_size: Record<string, never> | null;
            /** @example L */
            bike_size: Record<string, never> | null;
            /** @example 1540 */
            total_km: Record<string, never> | null;
            /** @example 3600 */
            total_time_min: Record<string, never> | null;
            /** @example false */
            has_front_suspension: boolean;
            /** @example false */
            has_rear_suspension: boolean;
            /** @example 2024-01-01T12:00:00.000Z */
            created_at: Record<string, never> | null;
            /** @example 2024-01-02T12:00:00.000Z */
            updated_at: Record<string, never> | null;
            /** @example Carbon */
            frame_material: Record<string, never> | null;
            /** @example false */
            is_deleted: Record<string, never> | null;
            /** @example null */
            deleted_at: Record<string, never> | null;
            /** @example b12345678 */
            strava_gear_id: Record<string, never> | null;
            /** @example My Enduro Bike */
            strava_name: Record<string, never> | null;
        };
        SearchBikeExternalResponseDto: {
            /** @example Orbea Rallon */
            name: string;
            /** @example Orbea 2025 */
            bikeBrand: string;
            /** @example https://example.com/bike-image.jpg */
            imageUrl: Record<string, never>;
            /** @example https://example.com/bike/1 */
            bikeUrl: string;
        };
        AssembleBikeComponentsDto: {
            component: components["schemas"]["CreateMountedComponentsDto"];
            /** @example Fork */
            component_name: string;
            /** @example 15 */
            component_group_id: number;
            /**
             * @description null for user-created types
             * @example component.fork
             */
            component_i18n_key: string | null;
            /**
             * @description The part sits on a side of the bike (front / rear)
             * @example true
             */
            has_position: boolean;
            /**
             * @description Every bike carries it, so it is saved even when left blank
             * @example true
             */
            essential: boolean;
        };
        BikeBrands: {
            /** @example Santa Cruz */
            bike_brand: string;
            /** @example 42 */
            id: number;
        };
        BikeModels: {
            /** @example Nomad */
            model_name: string;
            /** @example 42 */
            brand_id: number;
        };
        NewBikeFormDataDto: {
            bikeTypes: string[];
            bikeBrands: components["schemas"]["BikeBrands"][];
            bikeModels: components["schemas"]["BikeModels"][];
        };
        UpdateBikeDto: Record<string, never>;
        Attachment_BikeEventDto: {
            /** @example faktura.pdf */
            name: string;
            /** @example application/pdf */
            content_type: string;
            /** @example https://cdn.example.com/files/faktura.pdf */
            url: string;
        };
        Actions_BikeEventDto: {
            /** @example 1 */
            action_id: number;
            /** @example Replaced chain */
            description: string;
            /** @example 50 */
            partial_cost: number;
            /** @example false */
            part_replaced: boolean;
            /**
             * @description IDs of components involved in this action
             * @example [
             *       15,
             *       16
             *     ]
             */
            mounted_components_involved: string[];
        };
        Create_BikeEventDto: {
            /** @example 15 */
            bike_id: number;
            /** @example 15 */
            total_cost: number;
            attachment: components["schemas"]["Attachment_BikeEventDto"][] | null;
            /** @example Replaced chain and cleaned drivetrain */
            note: string | null;
            actions_done: components["schemas"]["Actions_BikeEventDto"][];
        };
        MountedComponentDto: {
            /** @example 45 */
            id: number;
            /** @example Shimano XT M8100 */
            component_desc: Record<string, never> | null;
            /** @example front */
            position: Record<string, never> | null;
            /** @example Brake */
            component_type: string;
            /**
             * @description null for user-created types
             * @example component.brakeCaliper
             */
            component_type_i18n_key: Record<string, never> | null;
            /**
             * @description total_km frozen at service time
             * @example 1240
             */
            km_at_time: Record<string, never> | null;
            /**
             * @description total_time_min frozen at service time
             * @example 3780
             */
            time_min_at_time: Record<string, never> | null;
            /**
             * @description drivetrain_km frozen at service time
             * @example 900
             */
            drivetrain_km_at_time: Record<string, never> | null;
            /**
             * @description suspension_min frozen at service time
             * @example 2100
             */
            suspension_min_at_time: Record<string, never> | null;
        };
        ActionsDoneDto: {
            /** @example 1 */
            action_id: number;
            /** @example Brake bleed */
            action_name: string;
            /**
             * @description null for user-created actions
             * @example action.bleed
             */
            action_i18n_key: Record<string, never> | null;
            /** @example 150 */
            partial_cost: Record<string, never> | null;
            /** @example false */
            replace_action: boolean;
            /** @example Replaced brake pads */
            note: Record<string, never> | null;
            mounted_components: components["schemas"]["MountedComponentDto"][];
        };
        AttachmentDto: {
            /** @example 1 */
            id: number;
            /** @example invoice.pdf */
            name: string;
            /** @example application/pdf */
            content_type: string;
            /** @example https://cdn.example.com/invoice.pdf */
            url: string;
        };
        Response_BikeEvent_Dto: {
            /** @example 1 */
            id: number;
            /** @example 15 */
            bike_id: number;
            /** @example Regular service */
            note: Record<string, never> | null;
            /** @example 350.5 */
            total_cost: number;
            /** Format: date-time */
            created_at: string;
            updated_at: Record<string, never> | null;
            actions_done: components["schemas"]["ActionsDoneDto"][];
            attachments: components["schemas"]["AttachmentDto"][];
        };
        ActionTagDto: {
            /** @example Full Flush */
            tag: string;
            /** @example actionTag.fullFlush */
            i18n_key: Record<string, never> | null;
        };
        ActionDto: {
            /** @example 1 */
            id: number;
            /** @example Brake bleed */
            action_name: string;
            /**
             * @description null for user-created actions
             * @example action.bleed
             */
            action_i18n_key: Record<string, never> | null;
            /** @example false */
            replace_action: boolean;
            tags: components["schemas"]["ActionTagDto"][];
            components: components["schemas"]["MountedComponentDto"][];
        };
        Response_ActionsOnGroup_Dto: {
            /** @example 1 */
            group_id: number;
            /** @example Brake System */
            group_name: string;
            /** @example componentGroup.brakes */
            group_i18n_key: Record<string, never> | null;
            /** @example false */
            side_choice: boolean;
            actions: components["schemas"]["ActionDto"][];
        };
        CustomComponentsDto: {
            /** @example 15 */
            component_group_id: number;
            /** @example 1 */
            user_id: number;
            /** @example Custom Component Name */
            component_type: string;
            /** @example false */
            ebike: boolean;
            /** @example true */
            has_position?: boolean | null;
        };
        Response_ComponentDto: {
            /** @example 15 */
            component_group_id: number;
            /** @example 1 */
            user_id: Record<string, never>;
            /** @example Custom Component Name */
            component_type: string;
            /**
             * @description null for user-created types
             * @example component.chain
             */
            i18n_key: Record<string, never> | null;
            /** @example false */
            ebike: boolean;
            /** @example true */
            has_position: boolean;
            /**
             * @description Every bike carries it, so it is saved even when left blank
             * @example true
             */
            essential: boolean;
        };
        Response_ComponentGroupDto: {
            /** @example 1 */
            id: number;
            /** @example Drivetrain */
            group_name: string;
            /** @example componentGroup.drivetrain */
            i18n_key: Record<string, never> | null;
            /** @example false */
            side_choice: boolean;
        };
        Response_MountedComponentsDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            bike_id: number;
            /** @example 12 */
            component_type_id: number;
            /** @example rear */
            position: Record<string, never> | null;
            /** @example 2026-03-26T10:00:00.000Z */
            mounted_at: Record<string, never> | null;
            /** @example null */
            removed_at: Record<string, never> | null;
            /** @example 2026-03-26T10:00:00.000Z */
            updated_at: Record<string, never> | null;
            /** @example 2026-03-26T10:00:00.000Z */
            created_at: Record<string, never> | null;
            /** @example 1200 */
            total_km: Record<string, never> | null;
            /** @example Mounted after spring service */
            note: Record<string, never> | null;
            /** @example true */
            is_active: Record<string, never> | null;
            /** @example false */
            is_deleted: Record<string, never> | null;
            /** @example null */
            deleted_at: Record<string, never> | null;
            /** @example Fox 38 Factory Grip2 */
            component_desc: Record<string, never> | null;
            /** @example 1200 */
            total_time_min: Record<string, never> | null;
            /** @example 80000 */
            drivetrain_km: Record<string, never> | null;
            /** @example 480 */
            suspension_min: Record<string, never> | null;
            /** @example 85 */
            health_index: Record<string, never> | null;
        };
        CreateOrganizationDto: {
            name: string;
        };
        OrganizationResponseDto: {
            id: number;
            name: string;
            created_at: Record<string, never>;
            updated_at: Record<string, never>;
        };
        AddMemberDto: {
            user_id: number;
            /** @example owner, admin, member */
            role_type: string;
        };
        OrganizationMemberResponseDto: {
            id: number;
            user_id: number;
            organization_id: number;
            role_type: string;
        };
        UpdateOrganizationDto: {
            name?: string;
        };
        ResponseStravaAuthorizeUrlDto: {
            /** @example https://www.strava.com/oauth/authorize?client_id=235898&state=a3f2... */
            url: string;
        };
        ResponseUnmatchedStravaGearDto: {
            /** @example 1 */
            user_id: number;
            /** @example 12345 */
            athlete_id: number;
            strava_bikes: unknown[][];
            bikecheck_bikes: unknown[][];
        };
        GearLinkDto: {
            /** @example b1234567 */
            stravaBikeId: Record<string, never> | null;
            /** @example 1 */
            bikecheckBikeId: number;
        };
        LinkStravaGearDto: {
            links: components["schemas"]["GearLinkDto"][];
        };
        ResponsePendingStravaDto: {
            /** @example 13579246810 */
            activity_id: string;
            /** @example b12345 */
            gear_id: Record<string, never> | null;
            /** @example 2026-08-19T06:12:00.000Z */
            started_at: string;
            /** @example 42 */
            distance_km: number;
            /** @example 96 */
            duration_min: number;
            /** @example 612 */
            elevation_up_m: number;
            /**
             * Format: date-time
             * @example 2026-08-19T06:40:00.000Z
             */
            created_at: string;
        };
        ResolvePendingActivityDto: {
            /** @example 1 */
            bikeId: number;
        };
        DeviceTokenDto: {
            /** @example caYcjw...:APA91b... */
            token: string;
            /** @example android */
            platform: string;
        };
        ResponseNotificationDto: {
            /** @example 1 */
            id: number;
            /** @example strava_unmatched_activity */
            type: string;
            /** @example Nepřiřazená aktivita ze Stravy */
            title: string;
            /** @example Kolo "Trek Fuel EX" ještě nemáš přiřazené */
            body: string;
            /**
             * @example {
             *       "gearId": "b12345"
             *     }
             */
            payload: Record<string, never> | null;
            /** @example false */
            is_read: boolean;
            /** @example null */
            read_at: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-06-16T12:00:00.000Z
             */
            created_at: string;
        };
        ResponseReportDto: {
            /** @example 1 */
            id: number;
            /** @example b1f7c0e2-2a3d-4e5f-8a9b-0c1d2e3f4a5b */
            public_token: string;
            /** @example https://app.bikecheck.com/r/b1f7c0e2-2a3d-4e5f-8a9b-0c1d2e3f4a5b */
            share_url: string;
            /** @example 42 */
            bike_id: number;
            /** @example 3 */
            view_count: number;
            /** @example null */
            last_viewed_at: Record<string, never> | null;
            /** @example false */
            revoked: boolean;
            /** @example null */
            expires_at: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-06-23T12:00:00.000Z
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "User getUser": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "User updateUser": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "User createUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Auth test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth createUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Auth getMe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Auth refreshUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Auth googleAuth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth googleReceiveToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Auth googleAuthRedirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            203: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    "Bike createBike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description CreateBikeWithComponentsDto serialized as JSON */
                    data: string;
                    /** Format: binary */
                    image?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"];
                };
            };
        };
    };
    "Bike searchBikeExternal": {
        parameters: {
            query: {
                bikeName: string;
                year: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchBikeExternalResponseDto"][];
                };
            };
        };
    };
    "Bike searchComponentsExternal": {
        parameters: {
            query: {
                bikeUrl: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleBikeComponentsDto"][];
                };
            };
        };
    };
    "Bike formOptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewBikeFormDataDto"];
                };
            };
        };
    };
    "Bike findUserBikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"][];
                };
            };
        };
    };
    "Bike findBike": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"];
                };
            };
        };
    };
    "Bike update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBikeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"];
                };
            };
        };
    };
    "Bike deleteSoft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"];
                };
            };
        };
    };
    "Bike deleteHard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBikeDto"];
                };
            };
        };
    };
    "BikeEvent create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create_BikeEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_BikeEvent_Dto"];
                };
            };
        };
    };
    "BikeEvent getActionsOnGroup": {
        parameters: {
            query: {
                groupId: number;
                bikeId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ActionsOnGroup_Dto"];
                };
            };
        };
    };
    "BikeEvent findAllBikeEvents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bikeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_BikeEvent_Dto"][];
                };
            };
        };
    };
    "BikeEvent findOne": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_BikeEvent_Dto"];
                };
            };
        };
    };
    "BikeEvent softDelete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_BikeEvent_Dto"];
                };
            };
        };
    };
    "BikeEvent hardDelete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_BikeEvent_Dto"];
                };
            };
        };
    };
    "Component createComponentType": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomComponentsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ComponentDto"];
                };
            };
        };
    };
    "Component getDefaultComponents": {
        parameters: {
            query: {
                ebike: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleBikeComponentsDto"][];
                };
            };
        };
    };
    "Component getGroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_ComponentGroupDto"][];
                };
            };
        };
    };
    "Component getMountedComponents": {
        parameters: {
            query: {
                bikeId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MountedComponentsDto"][];
                };
            };
        };
    };
    "Organization createOrganization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    "Organization getMembers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMemberResponseDto"][];
                };
            };
        };
    };
    "Organization addMember": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMemberResponseDto"];
                };
            };
        };
    };
    "Organization getOrganization": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    "Organization deleteOrganization": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Organization updateOrganization": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    "Organization removeMember": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Strava connectStrava": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseStravaAuthorizeUrlDto"];
                };
            };
        };
    };
    "Strava disconnectStrava": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Strava listUnmatchedStravaGear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUnmatchedStravaGearDto"];
                };
            };
        };
    };
    "Strava linkStravaGear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkStravaGearDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Strava listPendingActivities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePendingStravaDto"][];
                };
            };
        };
    };
    "Strava getPendingActivity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePendingStravaDto"];
                };
            };
        };
    };
    "Strava resolvePendingActivity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePendingActivityDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Notification registerFcmToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Notification list": {
        parameters: {
            query?: {
                unread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseNotificationDto"][];
                };
            };
        };
    };
    "Notification markRead": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Report listForBike": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bikeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseReportDto"][];
                };
            };
        };
    };
    "Report create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bikeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseReportDto"];
                };
            };
        };
    };
    "Report listMine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseReportDto"][];
                };
            };
        };
    };
    "Report revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Report getPublic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
