// Catalogue labels in every language a Report can be written in. A Report is a document,
// not a live view: its labels are resolved once at Export time and never looked up again
// (ADR 0011), which is why the server needs the text the client normally renders.
//
// Mirrors the catalogue namespaces - action, bikeType, componentGroup, component - of
// _frontend/bikecheck/src/i18n/locales, which stay the source of truth. A label renamed
// there must be renamed here, or Reports keep quoting the old wording.

type CatalogueLabels = Record<string, string>;

const en: CatalogueLabels = {
  'action.back': 'Back',
  'action.close': 'Close',
  'action.retry': 'Try again',
  'action.bleed': 'Bleed',
  'action.padsReplacement': 'Pad replacement',
  'action.caliperService': 'Caliper service',
  'action.rotorService': 'Rotor service',
  'action.leverReplacement': 'Lever replacement',
  'action.brakeHoseReplacement': 'Brake hose replacement',
  'action.chainLube': 'Chain lube',
  'action.chainReplacement': 'Chain replacement',
  'action.cassetteReplacement': 'Cassette replacement',
  'action.chainringReplacement': 'Chainring replacement',
  'action.derailleurIndexing': 'Derailleur indexing',
  'action.derailleurService': 'Derailleur service',
  'action.chainWearCheck': 'Chain wear check',
  'action.wearCheck': 'Wear check',
  'action.cableHousingReplacement': 'Cable and housing replacement',
  'action.bbService': 'Bottom bracket service',
  'action.drivetrainDetox': 'Drivetrain deep clean',
  'action.batterySwap': 'Battery replacement',
  'action.forkBasicService': 'Fork basic service',
  'action.forkFullService': 'Fork full service',
  'action.shockBasicService': 'Shock basic service',
  'action.shockFullService': 'Shock full service',
  'action.forkAdjusment': 'Fork setup',
  'action.shockAdjusment': 'Shock setup',
  'action.remoteLeverService': 'Remote lever service',
  'action.tireReplacement': 'Tire replacement',
  'action.sealantRefresh': 'Sealant refresh',
  'action.tubelessConversion': 'Tubeless conversion',
  'action.wheelTruing': 'Wheel truing',
  'action.hubService': 'Hub service',
  'action.hubBearingReplacement': 'Hub bearing replacement',
  'action.headsetService': 'Headset service',
  'action.headsetBearingReplacement': 'Headset bearing replacement',
  'action.boltTorqueCheck': 'Bolt torque check',
  'action.gripReplecament': 'Grip replacement',
  'action.dropperService': 'Dropper post service',
  'action.remoteCableReplaced': 'Remote cable replacement',
  'action.pivotBearingsReplacement': 'Frame pivot bearing replacement',
  'action.hangerReplacement': 'Hanger replacement',
  'action.hangerAlignment': 'Hanger alignment',
  'action.applyFrameShield': 'Frame protection film',
  'action.firmwareUpdate': 'Firmware update',
  'action.batteryCheck': 'Battery check',
  'action.hardwareMaintenance': 'Hardware maintenance',
  'action.systemDiagnostics': 'System diagnostics',
  'action.pedalService': 'Pedal service',
  'bikeType.road': 'Road',
  'bikeType.enduro': 'Enduro',
  'bikeType.trail': 'Trail',
  'bikeType.dh': 'DH',
  'bikeType.xc': 'XC',
  'bikeType.fatBike': 'Fat Bike',
  'bikeType.gravel': 'Gravel',
  'bikeType.dirt': 'Dirt',
  'bikeType.freeride': 'Freeride',
  'bikeType.ebike': 'E-bike',
  'componentGroup.suspension': 'Suspension',
  'componentGroup.frame': 'Frame',
  'componentGroup.cockpit': 'Cockpit',
  'componentGroup.saddleSeatpost': 'Saddle & Seatpost',
  'componentGroup.wheels': 'Wheels & Tires',
  'componentGroup.drivetrain': 'Drivetrain',
  'componentGroup.brakes': 'Brakes',
  'componentGroup.eBike': 'E-bike',
  'componentGroup.other': 'Other',
  'component.fork': 'Fork',
  'component.shock': 'Shock',
  'component.frame': 'Frame',
  'component.hanger': 'Derailleur hanger',
  'component.headset': 'Headset',
  'component.stem': 'Stem',
  'component.handlebar': 'Handlebar',
  'component.grips': 'Grips',
  'component.dropperLever': 'Dropper lever',
  'component.remoteLever': 'Remote lever',
  'component.saddle': 'Saddle',
  'component.seatpost': 'Seatpost',
  'component.rim': 'Rim',
  'component.tire': 'Tire',
  'component.hub': 'Hub',
  'component.axle': 'Axle',
  'component.inserts': 'Tire inserts',
  'component.valves': 'Valves',
  'component.sealant': 'Sealant',
  'component.derailleur': 'Derailleur',
  'component.shifter': 'Shifter',
  'component.crank': 'Crank',
  'component.chainring': 'Chainring',
  'component.bashguard': 'Bashguard',
  'component.cassette': 'Cassette',
  'component.chain': 'Chain',
  'component.chainGuide': 'Chain guide',
  'component.bottomBracket': 'Bottom bracket',
  'component.brakeCaliper': 'Brake caliper',
  'component.brakeLever': 'Brake lever',
  'component.brakeRotor': 'Brake rotor',
  'component.brakePad': 'Brake pads',
  'component.motor': 'Motor',
  'component.battery': 'Battery',
  'component.display': 'Display',
  'component.charger': 'Charger',
  'component.eBikeSystem': 'E-bike system',
  'component.pedals': 'Pedals',
  'component.brakes': 'Brakes',
};

const cs: CatalogueLabels = {
  'action.back': 'Zpět',
  'action.close': 'Zavřít',
  'action.retry': 'Zkusit znovu',
  'action.bleed': 'Odvzdušnění',
  'action.padsReplacement': 'Výměna destiček',
  'action.caliperService': 'Servis třmenu',
  'action.rotorService': 'Servis kotouče',
  'action.leverReplacement': 'Výměna páky',
  'action.brakeHoseReplacement': 'Výměna brzdové hadičky',
  'action.chainLube': 'Mazání řetězu',
  'action.chainReplacement': 'Výměna řetězu',
  'action.cassetteReplacement': 'Výměna kazety',
  'action.chainringReplacement': 'Výměna převodníku',
  'action.derailleurIndexing': 'Seřízení přehazovačky',
  'action.derailleurService': 'Servis přehazovačky',
  'action.chainWearCheck': 'Kontrola opotřebení řetězu',
  'action.wearCheck': 'Kontrola opotřebení',
  'action.cableHousingReplacement': 'Výměna lanek a bowdenů',
  'action.bbService': 'Servis středového složení',
  'action.drivetrainDetox': 'Hloubkové čištění pohonu',
  'action.batterySwap': 'Výměna baterie',
  'action.forkBasicService': 'Základní servis vidlice',
  'action.forkFullService': 'Kompletní servis vidlice',
  'action.shockBasicService': 'Základní servis tlumiče',
  'action.shockFullService': 'Kompletní servis tlumiče',
  'action.forkAdjusment': 'Seřízení vidlice',
  'action.shockAdjusment': 'Seřízení tlumiče',
  'action.remoteLeverService': 'Servis ovládací páčky',
  'action.tireReplacement': 'Výměna pláště',
  'action.sealantRefresh': 'Doplnění tmelu',
  'action.tubelessConversion': 'Přestavba na bezdušové',
  'action.wheelTruing': 'Centrování kola',
  'action.hubService': 'Servis náboje',
  'action.hubBearingReplacement': 'Výměna ložisek náboje',
  'action.headsetService': 'Servis hlavového složení',
  'action.headsetBearingReplacement': 'Výměna ložisek hlavového složení',
  'action.boltTorqueCheck': 'Kontrola utažení šroubů',
  'action.gripReplecament': 'Výměna gripů',
  'action.dropperService': 'Servis teleskopické sedlovky',
  'action.remoteCableReplaced': 'Výměna lanka ovladače',
  'action.pivotBearingsReplacement': 'Výměna ložisek rámu',
  'action.hangerReplacement': 'Výměna patky',
  'action.hangerAlignment': 'Rovnání patky',
  'action.applyFrameShield': 'Nalepení ochranné fólie',
  'action.firmwareUpdate': 'Aktualizace firmwaru',
  'action.batteryCheck': 'Kontrola baterie',
  'action.hardwareMaintenance': 'Údržba hardwaru',
  'action.systemDiagnostics': 'Diagnostika systému',
  'action.pedalService': 'Servis pedálů',
  'bikeType.road': 'Silniční',
  'bikeType.enduro': 'Enduro',
  'bikeType.trail': 'Trail',
  'bikeType.dh': 'DH',
  'bikeType.xc': 'XC',
  'bikeType.fatBike': 'Fat Bike',
  'bikeType.gravel': 'Gravel',
  'bikeType.dirt': 'Dirt',
  'bikeType.freeride': 'Freeride',
  'bikeType.ebike': 'E-bike',
  'componentGroup.suspension': 'Odpružení',
  'componentGroup.frame': 'Rám',
  'componentGroup.cockpit': 'Kokpit',
  'componentGroup.saddleSeatpost': 'Sedlo a sedlovka',
  'componentGroup.wheels': 'Kola',
  'componentGroup.drivetrain': 'Pohon',
  'componentGroup.brakes': 'Brzdy',
  'componentGroup.eBike': 'E-bike',
  'componentGroup.other': 'Ostatní',
  'component.fork': 'Vidlice',
  'component.shock': 'Tlumič',
  'component.frame': 'Rám',
  'component.hanger': 'Patka přehazovačky',
  'component.headset': 'Hlavové složení',
  'component.stem': 'Představec',
  'component.handlebar': 'Řídítka',
  'component.grips': 'Gripy',
  'component.dropperLever': 'Páčka teleskopické sedlovky',
  'component.remoteLever': 'Ovládací páčka',
  'component.saddle': 'Sedlo',
  'component.seatpost': 'Sedlovka',
  'component.rim': 'Ráfek',
  'component.tire': 'Plášť',
  'component.hub': 'Náboj',
  'component.axle': 'Osa',
  'component.inserts': 'Vložky do plášťů',
  'component.valves': 'Ventilky',
  'component.sealant': 'Tmel',
  'component.derailleur': 'Přehazovačka',
  'component.shifter': 'Řadicí páka',
  'component.crank': 'Kliky',
  'component.chainring': 'Převodník',
  'component.bashguard': 'Kryt převodníku',
  'component.cassette': 'Kazeta',
  'component.chain': 'Řetěz',
  'component.chainGuide': 'Vodítko řetězu',
  'component.bottomBracket': 'Středové složení',
  'component.brakeCaliper': 'Brzdový třmen',
  'component.brakeLever': 'Brzdová páka',
  'component.brakeRotor': 'Brzdový kotouč',
  'component.brakePad': 'Brzdové destičky',
  'component.motor': 'Motor',
  'component.battery': 'Baterie',
  'component.display': 'Displej',
  'component.charger': 'Nabíječka',
  'component.eBikeSystem': 'Systém e-biku',
  'component.pedals': 'Pedály',
  'component.brakes': 'Brzdy',
};

const LABELS: Record<string, CatalogueLabels> = { en, cs };

// What a Report falls back to when the owner never chose a language.
export const FALLBACK_REPORT_LANGUAGE = 'en';

// What a Report is priced in when the owner never chose a currency. Most of them are Czech.
export const FALLBACK_REPORT_CURRENCY = 'CZK';

// The language a Report is written in: the owner's, when we can write it.
export function reportLanguage(language: string | null | undefined): string {
  return language !== null && language !== undefined && language in LABELS ? language : FALLBACK_REPORT_LANGUAGE;
}

// One catalogue label as text. Seeded rows carry a key and are translated; a row a user
// created carries only the name they gave it, which no language translates.
export function catalogueLabel(language: string, i18nKey: string | null, fallback: string): string {
  if (i18nKey === null) {
    return fallback;
  }
  return LABELS[language]?.[i18nKey] ?? LABELS[FALLBACK_REPORT_LANGUAGE][i18nKey] ?? fallback;
}
