// Copies the catalogue names - what a Component Type and an Action are called in each
// language - from the app's locale files into a generated module the server can read.
// The app's JSON stays the one source; run `npm run catalogue:sync` after changing it.
import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const LOCALES_DIR = resolve(__dirname, '../../../../_frontend/bikecheck/src/i18n/locales');
const OUTPUT = resolve(__dirname, '../src/notification/catalogue-names.generated.ts');

const LANGUAGES = ['cs', 'en'] as const;
// The namespaces the catalogue's i18n keys live in: `component.chain`, `action.chainReplacement`.
const NAMESPACES = ['component', 'action'] as const;

type Names = Record<string, string>;

function flatten(namespace: string, entries: Record<string, unknown>): Names {
  const names: Names = {};
  for (const [key, value] of Object.entries(entries)) {
    if (typeof value === 'string') names[`${namespace}.${key}`] = value;
  }
  return names;
}

function readLanguage(language: string): Names {
  const raw = JSON.parse(readFileSync(resolve(LOCALES_DIR, `${language}.json`), 'utf-8')) as Record<string, unknown>;
  return Object.assign({}, ...NAMESPACES.map((ns) => flatten(ns, (raw[ns] ?? {}) as Record<string, unknown>)));
}

const names = Object.fromEntries(LANGUAGES.map((language) => [language, readLanguage(language)]));

const header = `// Generated by scripts/sync-catalogue-names.ts from the app's locale files. Do not edit;
// run \`npm run catalogue:sync\` after changing a catalogue name in the app.
`;
writeFileSync(OUTPUT, `${header}export const CATALOGUE_NAMES = ${JSON.stringify(names, null, 2)} as const;\n`);
// Written the way the repo's lint expects it, so a regeneration never fails the lint.
execSync(`npx prettier --write "${OUTPUT}"`, { stdio: 'ignore' });

const count = Object.values(names).map((n) => Object.keys(n).length);
console.log(`Wrote ${OUTPUT} (${LANGUAGES.map((l, i) => `${l}: ${count[i]}`).join(', ')})`);
